### ISSUE TITLE
ImportError: cannot import name 'build_augmentation' from 'models.utils' 

### ISSUE THREAD

**Issue by A7eNg** [YangHai-1218/SCFlow#4]
Hi,

Thanks for your promising work, when I'm reproducing the code, there is an ImportError

ImportError: cannot import name 'build_augmentation' from 'models.utils' (/data_sata/WorkSpace_ZT/scflow/models/utils/__init__.py)

![image](https://github.com/YangHai-1218/SCFlow/assets/48305976/617c489d-984e-46bb-86d9-c12fa14fe8fc)

I can not find this module in utils, is there any missing file?

**Comment by YangHai-1218** [comment]
Sorry about this bug. I have fixed it. Please try again!

**Comment by A7eNg** [comment]
Thanks! However, there are still several problems during my implementation:
1. When performing test, setting scflow.py line 1 as `_base_ = '../refine_datasets/ycbv_real.py'`, there is an error: 
![image](https://github.com/YangHai-1218/SCFlow/assets/48305976/467aeb18-4fb9-417d-b396-fef6b8cbf95c)
2. When performing train, setting scflow.py line 1 as `_base_ = '../refine_datasets/ycbv_mixpbr.py'`, there is an error:
![image](https://github.com/YangHai-1218/SCFlow/assets/48305976/e9a09e62-c600-40a1-918e-bcd77ecce1b6)
Thanks again for your kind help!

**Comment by YangHai-1218** [comment]
Please pull the latest code and try again!

**Comment by A7eNg** [comment]
Thanks! The test works fine, but training in mixpbr still failed. Here is the Traceback:

![image](https://github.com/YangHai-1218/SCFlow/assets/48305976/a7c1e8b7-267c-4878-9507-5a5f93003b31)

**Comment by YangHai-1218** [comment]
Please try again. Feel free to let me know if there are other problems. Thanks!

**Comment by A7eNg** [comment]
Thanks very much for your help, could you please upload the code about evaluate on LM and LM-O datasets and code for evaluate on BOP metrics?

**Comment by cainiao1888** [comment]
Traceback (most recent call last):
  File "/home/www/program-file/gxycx/SCFlow-main/train.py", line 19, in &lt;module&gt;
    from datasets import build_dataset, MultiSourceSampler
ImportError: cannot import name 'MultiSourceSampler' from 'datasets' (/home/www/program-file/gxycx/SCFlow-main/datasets/__init__.py)

**Comment by zhangjy328** [comment]
Hello, I have also encountered an issue: the lack of LOSSES.
Traceback (most recent call last):
  File "/home/zjy/models/SCFlow/train.py", line 18, in <module>
    from models import build_refiner
  File "/home/zjy/models/SCFlow/models/__init__.py", line 1, in <module>
    from .loss import LOSSES, build_loss
ImportError: cannot import name 'LOSSES' from 'models.loss'
